/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_c1;

import Pojos.Token;
import Pojos.Variable;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erik
 */
public class Principal extends javax.swing.JFrame {

    private analizador.Lexer lexer;
    private analizador.parser parser;
    public static ArrayList<Pojos.err> errorLexer;
    public static ArrayList<Token> token;
    public static HashMap<String,Variable> lista_variable;
    private NumeroLinea n;

    /**
     * Creates new form Principal
     */
    public Principal() {
        archivo = null;
        token = new ArrayList<>();
        errorLexer = new ArrayList<>();
        lista_variable = new HashMap<>();
        initComponents();
        n = new NumeroLinea(txt_editor);
        jScrollPane1.setRowHeaderView(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_editor = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPlano = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        navigator = new javax.swing.JEditorPane();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_console = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_editor.setColumns(20);
        txt_editor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_editor.setRows(5);
        jScrollPane1.setViewportView(txt_editor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Edicion", jPanel1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pagina Web Resultante", "Reporte de Tokens", "Errores Lexicos", "Errores Sintacticos" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Abrir con navegador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPlano.setEditable(false);
        txtPlano.setColumns(20);
        txtPlano.setRows(5);
        jScrollPane4.setViewportView(txtPlano);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Texto Plano", jPanel7);

        navigator.setEditable(false);
        jScrollPane5.setViewportView(navigator);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Vista Html", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Resultados", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        txt_console.setEditable(false);
        txt_console.setBackground(new java.awt.Color(153, 153, 153));
        txt_console.setColumns(20);
        txt_console.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_console.setForeground(new java.awt.Color(255, 255, 255));
        txt_console.setRows(5);
        jScrollPane2.setViewportView(txt_console);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consola", jPanel5);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Valor", "Fila", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Variables", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(102, 50));
        jMenuBar1.setRequestFocusEnabled(false);

        jMenu1.setText("Archivo");
        jMenu1.setPreferredSize(new java.awt.Dimension(75, 21));

        jMenuItem1.setText("Nuevo Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Abrir Archivo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Guardar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Guardar Como");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Compilar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenu2.setPreferredSize(new java.awt.Dimension(75, 21));

        jMenuItem6.setText("Manual de Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Manual Tecnico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Acerca De");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    java.io.File archivo;
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JOptionPane.showMessageDialog(null, "CopyRight \nErik Gerardo Flores Diaz \n201701066", "Acerca De", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /* NUEVO ARCHIVO */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(archivo==null){
            txt_editor.setText("");
            archivo = null;
        }
        else{
            int op = JOptionPane.showConfirmDialog(null, "Hay un archivo abierto, desea crear uno nuevo?","",JOptionPane.YES_NO_OPTION);
            if(op == JOptionPane.YES_OPTION){
                archivo = null;
                txt_editor.setText("");
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /* ABRIR ARCHIVO */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser nuevo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Entrada","uweb");
        nuevo.setFileFilter(filtro);
        nuevo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = nuevo.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION) {
            archivo = nuevo.getSelectedFile();
            txt_editor.setText("");
            try {
                Scanner scn = new Scanner(archivo);
                while(scn.hasNext()){
                    txt_editor.insert(scn.nextLine() + "\n", txt_editor.getText().length());
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /* GUARDAR ARCHIVO */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(archivo!=null){
            BufferedWriter bw = null;
            try {
                bw = new BufferedWriter(new FileWriter(archivo));
                bw.write(txt_editor.getText());
                JOptionPane.showMessageDialog(null, "Archivo guardado","Congrats!",JOptionPane.INFORMATION_MESSAGE);
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            finally{
                if(bw!=null){
                    try{
                        bw.close();
                    }
                    catch(IOException ex){
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        else{
            try{
                JFileChooser nuevo =new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Entrada","uweb");
                nuevo.setFileFilter(filtro);
                nuevo.showSaveDialog(this);
                archivo = nuevo.getSelectedFile();
                if(archivo!=null){
                    FileWriter save = new FileWriter(archivo+".uweb");
                    save.write(txt_editor.getText());
                    save.close();
                    JOptionPane.showMessageDialog(null,"El archivo se a guardado Exitosamente","Congrats!",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch(IOException ex){
                JOptionPane.showMessageDialog(null,"Su archivo no se ha guardado","Advertencia",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /* GUAURDAR COMO */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try{
                JFileChooser nuevo =new JFileChooser();
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Entrada",".uweb");
                nuevo.setFileFilter(filtro);
                nuevo.showSaveDialog(this);
                archivo = nuevo.getSelectedFile();
                if(archivo!=null){
                    FileWriter save = new FileWriter(archivo+".uweb");
                    save.write(txt_editor.getText());
                    save.close();
                    JOptionPane.showMessageDialog(null,"El archivo se a guardado Exitosamente","Congrats!",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            catch(IOException ex){
                JOptionPane.showMessageDialog(null,"Su archivo no se ha guardado","Advertencia",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /* COMPILAR */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try{
            analizar();
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    /* MANUAL USUARIO */
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            File archivo = new File("Usuario.pdf");
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /* MANUAL TECNICO */
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            File archivo = new File("Tecnico.pdf");
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if(jComboBox1.getSelectedIndex()==0){
                File file = new File("index.html");
                Desktop.getDesktop().open(file);
            }
            else if(jComboBox1.getSelectedIndex()==1){
                File file = new File("Tokens.html");
                Desktop.getDesktop().open(file);
            }
            else if(jComboBox1.getSelectedIndex()==2){
                File file = new File("ReporteLexer.html");
                Desktop.getDesktop().open(file);
            }
            else if(jComboBox1.getSelectedIndex()==3){
                File file = new File("ReporteParser.html");
                Desktop.getDesktop().open(file);
            }
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txt_console.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    private void analizar(){
        String input = txt_editor.getText();
        lexer = new analizador.Lexer(new BufferedReader(new StringReader(input)));
        parser = new analizador.parser(lexer,txt_console);
        token.clear();
        errorLexer.clear();
        txt_console.setText("");
        try {
            parser.parse();
            addTable();
            generaHtml();
            reporteTokens();
            reporteLexer();
            reporteSintactico();
            /*for(Pojos.Token t : token){
                System.out.println(t.toString());
            }*/
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }


    public void reporteTokens() throws IOException{
            BufferedWriter bw;
        File file = new File("Tokens.html");
        if(!file.exists()){
            file.createNewFile();
        }
        bw = new BufferedWriter(new FileWriter(file));
        bw.write("<html>\n" +
                "<head>\n" +
                "<meta charset=\"utf-8\" />\n" +
                "<title>Reporte de Tokens</title>\n" +
                "<meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; width=device-width;\">\n" +
                "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n" +
                "</head>\n" +
                "<body>\n" +
                "<div class=\"table-title\">\n" +
                "<h3>Reporte de Tokens</h3>\n" +
                "</div>\n" +
                "\n" +
                "<table class=\"table-fill\">\n" +
                "<thead>\n" +
                "<tr>\n" +
                "<th class=\"text-left\">No.</th>\n" +
                "<th class=\"text-left\">Token</th>\n" +
                "<th class=\"text-left\">Lexema</th>\n" +
                "<th class=\"text-left\">Fila</th>	\n" +
                "<th class=\"text-left\">Columna</th>	\n" +
                "</tr>\n" +
                "</thead>\n" +
                "<tbody class=\"table-hover\">");
        int n = 0;
        for(Token t: token){
            bw.write("<tr>");
            bw.write("<td class=\"text-left\">"+ n +"</td>");
            bw.write("<td class=\"text-left\">"+ t.getToken() +"</td>");
            bw.write("<td class=\"text-left\">"+ t.getLexema() +"</td>");
            bw.write("<td class=\"text-left\">"+ t.getFila() +"</td>");
            bw.write("<td class=\"text-left\">"+ t.getColumna() +"</td>");
            bw.write("</tr>");
            n++;
        }
        bw.write("</tbody>\n" +
                "</table>\n" +
                "</body>\n" +
                "</html>");
        bw.close();
    }

    public void reporteLexer() throws IOException{
             BufferedWriter bw;
        File file = new File("ReporteLexer.html");
        if(!file.exists()){
            file.createNewFile();
        }
        bw = new BufferedWriter(new FileWriter(file));
        bw.write("<html>\n" +
                "<head>\n" +
                "<meta charset=\"utf-8\" />\n" +
                "<title>Reporte de Errores Lexicos</title>\n" +
                "<meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; width=device-width;\">\n" +
                "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n" +
                "</head>\n" +
                "<body>\n" +
                "<div class=\"table-title\">\n" +
                "<h3>Reporte de Errores Lexicos</h3>\n" +
                "</div>\n" +
                "\n" +
                "<table class=\"table-fill\">\n" +
                "<thead>\n" +
                "<tr>\n" +
                "<th class=\"text-left\">No.</th>\n" +
                "<th class=\"text-left\">Error</th>\n" +
                "<th class=\"text-left\">Fila</th>	\n" +
                "<th class=\"text-left\">Columna</th>	\n" +
                "</tr>\n" +
                "</thead>\n" +
                "<tbody class=\"table-hover\">");
        int n = 0;
        for(Pojos.err e: errorLexer){
            bw.write("<tr>");
            bw.write("<td class=\"text-left\">"+ n +"</td>");
            bw.write("<td class=\"text-left\">"+ e.getError() +"</td>");
            bw.write("<td class=\"text-left\">"+ e.getFila() +"</td>");
            bw.write("<td class=\"text-left\">"+ e.getColumna() +"</td>");
            bw.write("</tr>");
            n++;
        }
        bw.write("</tbody>\n" +
                "</table>\n" +
                "</body>\n" +
                "</html>");
        bw.close();
    }

    public void reporteSintactico() throws IOException{
        BufferedWriter bw;
        File file = new File("ReporteParser.html");
        if(!file.exists()){
            file.createNewFile();
        }
        bw = new BufferedWriter(new FileWriter(file));
        bw.write("<html>\n" +
                "<head>\n" +
                "<meta charset=\"utf-8\" />\n" +
                "<title>Reporte de Errores Sintacticoss</title>\n" +
                "<meta name=\"viewport\" content=\"initial-scale=1.0; maximum-scale=1.0; width=device-width;\">\n" +
                "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n" +
                "</head>\n" +
                "<body>\n" +
                "<div class=\"table-title\">\n" +
                "<h3>Reporte de Errores Sintacticos</h3>\n" +
                "</div>\n" +
                "\n" +
                "<table class=\"table-fill\">\n" +
                "<thead>\n" +
                "<tr>\n" +
                "<th class=\"text-left\">No.</th>\n" +
                "<th class=\"text-left\">Error</th>\n" +
                "<th class=\"text-left\">Fila</th>	\n" +
                "<th class=\"text-left\">Columna</th>	\n" +
                "</tr>\n" +
                "</thead>\n" +
                "<tbody class=\"table-hover\">");

        if(parser.err !=null){
            bw.write("<tr>");
            bw.write("<td class=\"text-left\"> 1 </td>");
            bw.write("<td class=\"text-left\">No se esperaba este  componente: "+ parser.err.getError() +"</td>");
            bw.write("<td class=\"text-left\">"+ parser.err.getFila() +"</td>");
            bw.write("<td class=\"text-left\">"+ parser.err.getColumna() +"</td>");
            bw.write("</tr>");
        }
        bw.write("</tbody>\n" +
                "</table>\n" +
                "</body>\n" +
                "</html>");
        bw.close();
    }

    public void mostrarPage(){
        String url = System.getProperty("user.dir") + "\\index.html";
        File rec = new File(url);
        try {
            navigator.setPage(rec.toURI().toURL());
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addTable() {
        DefaultTableModel md = (DefaultTableModel) jTable1.getModel();
        md.setRowCount(0);
        lista_variable.forEach((k,v) -> {
            Variable b = (Variable)v;
            md.addRow(new Object[] { b.getId(), b.getTipo(),b.getValue(),b.getFila(),b.getColumna()});
        });
 }

    private void generaHtml(){
        BufferedWriter bw = null;
        try{
            FileWriter save = new FileWriter("index.html");
            save.write(parser.bf.toString());
            save.close();
            mostrarPage();
            txtPlano.setText(parser.bf.toString());
        }
        catch(Exception ex){

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JEditorPane navigator;
    private javax.swing.JTextArea txtPlano;
    private javax.swing.JTextArea txt_console;
    private javax.swing.JTextArea txt_editor;
    // End of variables declaration//GEN-END:variables
}
