
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int num = 5;
  public static final int cierra = 3;
  public static final int error = 1;
  public static final int abre = 2;
  public static final int coma = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abre",
  "cierra",
  "coma",
  "num"
  };
}

