
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rgaleria = 10;
  public static final int llavederecha = 14;
  public static final int cadena = 2;
  public static final int coma = 18;
  public static final int grabar = 4;
  public static final int corcheteizquierdo = 17;
  public static final int por = 27;
  public static final int abre = 21;
  public static final int num = 24;
  public static final int puntosxy = 7;
  public static final int corchetederecho = 16;
  public static final int menos = 26;
  public static final int ejey = 6;
  public static final int ejex = 5;
  public static final int div = 28;
  public static final int menos1 = 29;
  public static final int igual = 15;
  public static final int EOF = 0;
  public static final int id = 23;
  public static final int cierra = 22;
  public static final int varglo = 3;
  public static final int error = 1;
  public static final int grali = 8;
  public static final int signoc = 20;
  public static final int signoa = 19;
  public static final int llaveizquierda = 13;
  public static final int mas = 25;
  public static final int dexyli = 9;
  public static final int dospuntos = 11;
  public static final int puntoycoma = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cadena",
  "varglo",
  "grabar",
  "ejex",
  "ejey",
  "puntosxy",
  "grali",
  "dexyli",
  "rgaleria",
  "dospuntos",
  "puntoycoma",
  "llaveizquierda",
  "llavederecha",
  "igual",
  "corchetederecho",
  "corcheteizquierdo",
  "coma",
  "signoa",
  "signoc",
  "abre",
  "cierra",
  "id",
  "num",
  "mas",
  "menos",
  "por",
  "div",
  "menos1"
  };
}

