
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int R_SETANCHO = 32;
  public static final int R_GETTEXTO = 36;
  public static final int MENOR_IGUAL = 61;
  public static final int R_SETCONTENIDO = 43;
  public static final int R_GETALINEACION = 46;
  public static final int R_GETPATH = 33;
  public static final int R_SETBORDE = 47;
  public static final int LLAVEIZQUIERDA = 66;
  public static final int R_IMAGEN = 12;
  public static final int R_CREARBOTON = 37;
  public static final int R_CREARTEXTOB = 42;
  public static final int R_FONDO = 8;
  public static final int R_CREARTEXTOA = 41;
  public static final int MAYOR = 60;
  public static final int R_SETALTO = 31;
  public static final int TEXTO = 24;
  public static final int CIERRA_ETIQUETA = 23;
  public static final int R_CREARPARRAFO = 78;
  public static final int R_GETCONTENIDO = 44;
  public static final int POR = 54;
  public static final int R_CREARIMAGEN = 40;
  public static final int R_TABLA = 11;
  public static final int NOT = 72;
  public static final int R_GETALTO = 34;
  public static final int CONCATENACION = 56;
  public static final int R_TRUE = 28;
  public static final int CIERRA = 58;
  public static final int NUM = 22;
  public static final int R_CIERRAHS = 49;
  public static final int CORCHETEIZQUIERDA = 68;
  public static final int COMA = 51;
  public static final int R_ELSE = 75;
  public static final int R_FALSE = 29;
  public static final int ENTERO = 26;
  public static final int R_GETANCHO = 35;
  public static final int SLASH = 2;
  public static final int R_ECHO = 73;
  public static final int R_PARRAFO = 9;
  public static final int CORCHETEDERECHA = 69;
  public static final int IGUAL = 3;
  public static final int R_INSERTAR = 77;
  public static final int R_CREARTABLA = 38;
  public static final int R_TITULO = 6;
  public static final int DECIMAL = 27;
  public static final int PUNTOYCOMA = 50;
  public static final int VARIABLE = 79;
  public static final int MENOS = 53;
  public static final int MENOR = 59;
  public static final int R_COLUMNAC = 18;
  public static final int MAS = 52;
  public static final int R_SETTEXTO = 48;
  public static final int R_CUERPO = 7;
  public static final int VAR2 = 81;
  public static final int VAR1 = 80;
  public static final int EOF = 0;
  public static final int R_COLUMNA = 19;
  public static final int IGUAL_LOGICO = 65;
  public static final int R_ESPACIO = 16;
  public static final int R_FILA = 17;
  public static final int ENTRE = 55;
  public static final int R_CLICKBOTON = 39;
  public static final int OR = 71;
  public static final int error = 1;
  public static final int R_REPETIR = 76;
  public static final int R_SALTO = 10;
  public static final int ID = 21;
  public static final int MENOS1 = 62;
  public static final int R_COMPI = 4;
  public static final int R_CABECERA = 5;
  public static final int CADENA = 20;
  public static final int DESIGUAL = 64;
  public static final int R_BOTON = 15;
  public static final int R_SETPATH = 30;
  public static final int R_SETALINEACION = 45;
  public static final int AND = 70;
  public static final int R_IF = 74;
  public static final int ABRE = 57;
  public static final int LLAVEDERECHA = 67;
  public static final int MAYOR_IGUAL = 63;
  public static final int R_TEXTOB = 14;
  public static final int R_TEXTOA = 13;
  public static final int ABRE_HS = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SLASH",
  "IGUAL",
  "R_COMPI",
  "R_CABECERA",
  "R_TITULO",
  "R_CUERPO",
  "R_FONDO",
  "R_PARRAFO",
  "R_SALTO",
  "R_TABLA",
  "R_IMAGEN",
  "R_TEXTOA",
  "R_TEXTOB",
  "R_BOTON",
  "R_ESPACIO",
  "R_FILA",
  "R_COLUMNAC",
  "R_COLUMNA",
  "CADENA",
  "ID",
  "NUM",
  "CIERRA_ETIQUETA",
  "TEXTO",
  "ABRE_HS",
  "ENTERO",
  "DECIMAL",
  "R_TRUE",
  "R_FALSE",
  "R_SETPATH",
  "R_SETALTO",
  "R_SETANCHO",
  "R_GETPATH",
  "R_GETALTO",
  "R_GETANCHO",
  "R_GETTEXTO",
  "R_CREARBOTON",
  "R_CREARTABLA",
  "R_CLICKBOTON",
  "R_CREARIMAGEN",
  "R_CREARTEXTOA",
  "R_CREARTEXTOB",
  "R_SETCONTENIDO",
  "R_GETCONTENIDO",
  "R_SETALINEACION",
  "R_GETALINEACION",
  "R_SETBORDE",
  "R_SETTEXTO",
  "R_CIERRAHS",
  "PUNTOYCOMA",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "CONCATENACION",
  "ABRE",
  "CIERRA",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MENOS1",
  "MAYOR_IGUAL",
  "DESIGUAL",
  "IGUAL_LOGICO",
  "LLAVEIZQUIERDA",
  "LLAVEDERECHA",
  "CORCHETEIZQUIERDA",
  "CORCHETEDERECHA",
  "AND",
  "OR",
  "NOT",
  "R_ECHO",
  "R_IF",
  "R_ELSE",
  "R_REPETIR",
  "R_INSERTAR",
  "R_CREARPARRAFO",
  "VARIABLE",
  "VAR1",
  "VAR2"
  };
}

