
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int div = 5;
  public static final int coma = 6;
  public static final int puntocoma = 7;
  public static final int cadena = 11;
  public static final int decimal = 9;
  public static final int EOF = 0;
  public static final int menos = 3;
  public static final int caracter = 12;
  public static final int entero = 8;
  public static final int error = 1;
  public static final int por = 4;
  public static final int cierra = 14;
  public static final int booleano = 10;
  public static final int menos1 = 15;
  public static final int abre = 13;
  public static final int mas = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "coma",
  "puntocoma",
  "entero",
  "decimal",
  "booleano",
  "cadena",
  "caracter",
  "abre",
  "cierra",
  "menos1"
  };
}

